version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    labels:
      traefik.enable: true
      traefik.http.routers.me_soloengine_in.rule: Host(`me.soloengine.in`)
      traefik.http.routers.me_soloengine_in.entrypoints: web
      traefik.http.services.me_soloengine_in.loadbalancer.server.port: 80
