version: "3.8"

services:
  php:
    build:
      context: .docker/php
    volumes:
      - ./public:/var/www/html
    networks:
      - dokploy-network
    expose:
      - 9000
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./public:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 80
    depends_on:
      - php
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true

      # HTTP router to redirect to HTTPS
      - traefik.http.routers.me-http.rule=Host(`me.soloengine.in`)
      - traefik.http.routers.me-http.entrypoints=web
      - traefik.http.routers.me-http.middlewares=redirect-to-https

      # HTTPS router serving traffic
      - traefik.http.routers.me-https.rule=Host(`me.soloengine.in`)
      - traefik.http.routers.me-https.entrypoints=websecure
      - traefik.http.routers.me-https.tls.certresolver=letsencrypt
      - traefik.http.routers.me-https.service=me-service

      # Service definition
      - traefik.http.services.me-service.loadbalancer.server.port=80

      # Middleware to redirect HTTP to HTTPS
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

    restart: unless-stopped

  wkhtmltopdf:
    build:
      context: .docker/wkhtmltopdf
    networks:
      - dokploy-network
    restart: unless-stopped

networks:
  dokploy-network:
    external: true