services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "mkdir -p /var/www/html/data &&
               chown -R www-data:www-data /var/www/html &&
               chmod -R 755 /var/www/html &&
               chmod 777 /var/www/html/data &&
               apache2-foreground"
    volumes:
      - .:/var/www/html
      - portfolio-data:/var/www/html/data
    networks:
      - dokploy-network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.me_soloengine_in.rule=Host(`me.soloengine.in`)"
        - "traefik.http.routers.me_soloengine_in.entrypoints=web"
        - "traefik.http.routers.me_soloengine_in.tls=false"
        - "traefik.http.services.me_soloengine_in.loadbalancer.server.port=80"

networks:
  dokploy-network:
    external: true

volumes:
  portfolio-data:
    driver: local